package io.kformik.ksp

import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration

/**
 * Symbol processor that emits a `<Name>Paths` object for every `@FormValues` data class.
 *
 * Example input:
 *
 * ```kotlin
 * @FormValues data class LoginValues(val email: String, val password: String)
 * ```
 *
 * Generated output:
 *
 * ```kotlin
 * object LoginValuesPaths {
 *     const val email: String = "email"
 *     const val password: String = "password"
 * }
 * ```
 *
 * Nested example:
 *
 * ```kotlin
 * @FormValues data class AddressValues(val city: String, val country: String)
 * @FormValues data class UserValues(val name: String, val address: AddressValues)
 * ```
 *
 * Generated:
 *
 * ```kotlin
 * object UserValuesPaths {
 *     const val name: String = "name"
 *     object address {
 *         const val city: String = "address.city"
 *         const val country: String = "address.country"
 *     }
 * }
 * ```
 *
 * Limitations (deliberate in this proof-of-concept):
 *  - `List<...>` properties are emitted as plain `String` constants pointing at the array path
 *    (e.g. `friends: String = "friends"`). Per-index access still uses string literals like
 *    `"${LoginValuesPaths.friends}[0]"`.
 *  - Recursive type references would loop; the processor caps at depth 8.
 */
class FormValuesProcessor(private val env: SymbolProcessorEnvironment) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val targets = resolver.getSymbolsWithAnnotation(FormValues::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .toList()
        if (targets.isEmpty()) return emptyList()

        // Pre-build a map of (qualifiedName → KSClassDeclaration) so the recursive emitter can
        // inline nested @FormValues types.
        val byName: Map<String, KSClassDeclaration> = targets
            .mapNotNull { decl -> decl.qualifiedName?.asString()?.let { it to decl } }
            .toMap()

        targets.forEach { decl ->
            emit(decl, byName)
            emitUpdater(decl, byName)
        }
        return emptyList()
    }

    private fun emit(decl: KSClassDeclaration, byName: Map<String, KSClassDeclaration>) {
        val pkg = decl.packageName.asString()
        val name = decl.simpleName.asString()
        val pathsName = "${name}Paths"

        val file = env.codeGenerator.createNewFile(
            dependencies = com.google.devtools.ksp.processing.Dependencies(aggregating = false),
            packageName = pkg,
            fileName = pathsName,
        )

        file.bufferedWriter().use { w ->
            if (pkg.isNotEmpty()) w.appendLine("package $pkg").appendLine()
            w.appendLine("// Generated by io.kformik.ksp.FormValuesProcessor. Do not edit.")
            w.appendLine("@Suppress(\"ConstPropertyName\", \"ObjectPropertyName\")")
            w.appendLine("object $pathsName {")
            emitProperties(w, decl, prefix = "", indent = "    ", byName, depth = 0)
            w.appendLine("}")
        }
    }

    /**
     * Emit a `<Name>Updater : io.kformik.ValuesUpdater<Name>` object alongside the Paths object.
     *
     * Generated shape (flat data class):
     *
     * ```kotlin
     * object LoginValuesUpdater : io.kformik.ValuesUpdater<LoginValues> {
     *     override fun getAt(values: LoginValues, path: String): Any? = when (path) {
     *         "email" -> values.email
     *         "password" -> values.password
     *         else -> null
     *     }
     *     override fun setAt(values: LoginValues, path: String, value: Any?): LoginValues = when (path) {
     *         "email" -> values.copy(email = value as String)
     *         "password" -> values.copy(password = value as String)
     *         else -> error("Unknown path: ${"$"}path")
     *     }
     *     override fun leafPaths(values: LoginValues): Set<String> = setOf("email", "password")
     * }
     * ```
     *
     * For nested `@FormValues` types, both `getAt` and `setAt` delegate to the nested type's
     * updater for the prefix-matched sub-path. `leafPaths` recursively flattens.
     *
     * Limitations (deliberate in this v1.4 PoC):
     *  - `List<...>` properties are returned as-is by `getAt`; `setAt` overwrites the entire list.
     *    Per-index updates (`tags[0]`) still work via the runtime `MapValuesUpdater` if you use
     *    a `Map`-based form; with a typed `data class`, list paths must be handled manually.
     *  - `Map<...>` properties: same as List — full overwrite only.
     *  - Generic types, sealed types, abstract types: not supported.
     */
    private fun emitUpdater(decl: KSClassDeclaration, byName: Map<String, KSClassDeclaration>) {
        val pkg = decl.packageName.asString()
        val name = decl.simpleName.asString()
        val updaterName = "${name}Updater"

        val file = env.codeGenerator.createNewFile(
            dependencies = com.google.devtools.ksp.processing.Dependencies(aggregating = false),
            packageName = pkg,
            fileName = updaterName,
        )

        val props: List<UpdaterPropInfo> = decl.getAllProperties().map { p ->
            val resolved = p.type.resolve()
            val td = resolved.declaration as? KSClassDeclaration
            val fq = td?.qualifiedName?.asString()
            val nested = fq?.let { byName[it] }
            UpdaterPropInfo(
                name = p.simpleName.asString(),
                simpleTypeName = td?.simpleName?.asString() ?: "Any",
                isNested = nested != null && nested.classKind == ClassKind.CLASS,
                nestedSimpleName = nested?.simpleName?.asString(),
                nullable = resolved.isMarkedNullable,
            )
        }.toList()

        fun castFor(p: UpdaterPropInfo): String = p.simpleTypeName + if (p.nullable) "?" else ""

        file.bufferedWriter().use { w ->
            if (pkg.isNotEmpty()) w.appendLine("package $pkg").appendLine()
            w.appendLine("// Generated by io.kformik.ksp.FormValuesProcessor. Do not edit.")
            w.appendLine("@Suppress(\"UNCHECKED_CAST\", \"USELESS_CAST\")")
            w.appendLine("object $updaterName : io.kformik.ValuesUpdater<$name> {")

            // getAt — when (path) { "x" -> values.x; "nested.X" -> NestedUpdater.getAt(...); else -> null }
            w.appendLine("    override fun getAt(values: $name, path: String): Any? {")
            w.appendLine("        return when {")
            for (p in props) {
                w.appendLine("            path == \"${p.name}\" -> values.${p.name}")
                if (p.isNested && p.nestedSimpleName != null) {
                    val updaterRef = "${p.nestedSimpleName}Updater"
                    w.appendLine("            path.startsWith(\"${p.name}.\") -> $updaterRef.getAt(values.${p.name}, path.removePrefix(\"${p.name}.\"))")
                }
            }
            w.appendLine("            else -> null")
            w.appendLine("        }")
            w.appendLine("    }")
            w.appendLine()

            // setAt — when … copy(x = value as T) | copy(nested = NestedUpdater.setAt(...))
            w.appendLine("    override fun setAt(values: $name, path: String, value: Any?): $name {")
            w.appendLine("        return when {")
            for (p in props) {
                w.appendLine("            path == \"${p.name}\" -> values.copy(${p.name} = value as ${castFor(p)})")
                if (p.isNested && p.nestedSimpleName != null) {
                    val updaterRef = "${p.nestedSimpleName}Updater"
                    val castNested = p.nestedSimpleName + if (p.nullable) "?" else ""
                    w.appendLine("            path.startsWith(\"${p.name}.\") -> values.copy(${p.name} = $updaterRef.setAt(values.${p.name} as $castNested ?: error(\"Cannot recurse into null ${p.name}\"), path.removePrefix(\"${p.name}.\"), value))")
                }
            }
            w.appendLine("            else -> error(\"Unknown path: \$path\")")
            w.appendLine("        }")
            w.appendLine("    }")
            w.appendLine()

            // leafPaths — flatten own props; for nested, prefix the child's leafPaths with "<prop>."
            w.appendLine("    override fun leafPaths(values: $name): Set<String> {")
            w.appendLine("        val out = mutableSetOf<String>()")
            for (p in props) {
                if (p.isNested && p.nestedSimpleName != null) {
                    val updaterRef = "${p.nestedSimpleName}Updater"
                    val safeRecv = if (p.nullable) "values.${p.name}?.let { $updaterRef.leafPaths(it) } ?: emptySet()" else "$updaterRef.leafPaths(values.${p.name})"
                    w.appendLine("        $safeRecv.forEach { out += \"${p.name}.\$it\" }")
                } else {
                    w.appendLine("        out += \"${p.name}\"")
                }
            }
            w.appendLine("        return out.toSet()")
            w.appendLine("    }")
            w.appendLine("}")
        }
    }

    private data class UpdaterPropInfo(
        val name: String,
        val simpleTypeName: String,
        val isNested: Boolean,
        val nestedSimpleName: String?,
        val nullable: Boolean,
    )

    private fun emitProperties(
        w: java.io.BufferedWriter,
        decl: KSClassDeclaration,
        prefix: String,
        indent: String,
        byName: Map<String, KSClassDeclaration>,
        depth: Int,
    ) {
        if (depth > 8) return  // safety: cap recursion
        val props: Sequence<KSPropertyDeclaration> = decl.getAllProperties()
        for (prop in props) {
            val propName = prop.simpleName.asString()
            val resolved = prop.type.resolve()
            val typeDecl = resolved.declaration as? KSClassDeclaration
            val qualifiedTypeName = typeDecl?.qualifiedName?.asString()
            val nestedDecl = qualifiedTypeName?.let { byName[it] }

            val joinedPath = if (prefix.isEmpty()) propName else "$prefix.$propName"

            if (nestedDecl != null && nestedDecl.classKind == ClassKind.CLASS) {
                // Emit a nested object scope for the @FormValues child type.
                w.appendLine("${indent}object $propName {")
                emitProperties(w, nestedDecl, joinedPath, "$indent    ", byName, depth + 1)
                // Also expose the parent path itself as a constant under the nested scope.
                // Identifier is backtick-quoted because `$` isn't a legal identifier character.
                w.appendLine("$indent    const val `\$path`: String = \"$joinedPath\"")
                w.appendLine("$indent}")
            } else {
                w.appendLine("${indent}const val $propName: String = \"$joinedPath\"")
            }
        }
    }
}

class FormValuesProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        FormValuesProcessor(environment)
}
